#!/bin/bash

SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do
  # resolve $SOURCE until the file is no longer a symlink
  DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE"
done
DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"

LOG_FILE=$DIR/updateAllGoogleCalendars.log

cd $DIR
date > $LOG_FILE
python updateAllGoogleCalendars.py & >> $LOG_FILE

[ $? -ne 0 ] && echo "see <a href=\"file://$LOG_FILE\">log file</a> for details" | mail -s "updateAllGoogleCalendars.py failed" marv42+updateAllGoogleCalendars@gmail.com
