#!/bin/bash





# https://stackoverflow.com/a/246128
DIR="$( dirname $(readlink -f "$0") )"


LOG_FILE=$DIR/updateAllGoogleCalendars.log

JUST_THE_LATEST_PART_OF_THE_LOG_FILE=$( tail -1000 $LOG_FILE )
echo "$JUST_THE_LATEST_PART_OF_THE_LOG_FILE" > $LOG_FILE
date >> $LOG_FILE
echo DIR=$DIR >> $LOG_FILE

cd $DIR
./venv/bin/python3 ./updateAllGoogleCalendars.py 2>&1 >> $LOG_FILE

[ $? -ne 0 ] && echo "see <a href=\"file://$LOG_FILE\">log file</a> for details" | mail -s "updateAllGoogleCalendars.py failed" marv42+updateAllGoogleCalendars@gmail.com < /dev/null
